#!/usr/bin/env python3
"""
HF Queue Worker for OAE Compute Relay v0.1

Polls Supabase `compute_jobs`, claims one paid queued job, executes a small compute artifact,
and marks the job done/failed using RPCs.

Required environment variables for live mode:
- SUPABASE_URL=https://<project>.supabase.co
- SUPABASE_SERVICE_ROLE_KEY=<service role key>

Safe modes:
- --once: process at most one job
- --dry-run: claim nothing; validate config only
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import sys
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

WORKER_ID = os.getenv("OAE_WORKER_ID", "hf-queue-worker-v01")
SUPABASE_URL = os.getenv("SUPABASE_URL", "https://ubauxksvewtwwerkpbuo.supabase.co").rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "") or os.getenv("SERVICE_ROLE_KEY", "")


def utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def request_json(method: str, path: str, payload: Optional[Any] = None) -> Any:
    if not SUPABASE_SERVICE_ROLE_KEY:
        raise RuntimeError("SUPABASE_SERVICE_ROLE_KEY is not set")

    data = None if payload is None else json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(f"{SUPABASE_URL}{path}", data=data, method=method)
    req.add_header("content-type", "application/json")
    req.add_header("apikey", SUPABASE_SERVICE_ROLE_KEY)
    req.add_header("authorization", f"Bearer {SUPABASE_SERVICE_ROLE_KEY}")

    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            raw = resp.read().decode("utf-8")
            if not raw:
                return None
            return json.loads(raw)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8")
        raise RuntimeError(f"HTTP {exc.code} from {path}: {body}") from exc


def rpc(name: str, payload: Dict[str, Any]) -> Any:
    return request_json("POST", f"/rest/v1/rpc/{name}", payload)


def claim_next_job() -> Optional[Dict[str, Any]]:
    result = rpc("claim_next_compute_job", {"p_worker_id": WORKER_ID})
    if not result:
        return None
    if isinstance(result, list):
        return result[0] if result else None
    if isinstance(result, dict):
        return result
    return None


def complete_job(job_id: str, artifact_sha: str, result_payload: Dict[str, Any], artifact_url: Optional[str] = None) -> Any:
    return rpc("complete_compute_job", {
        "p_job_id": job_id,
        "p_artifact_sha256": artifact_sha,
        "p_result_payload": result_payload,
        "p_artifact_url": artifact_url,
    })


def fail_job(job_id: str, error: str, result_payload: Optional[Dict[str, Any]] = None) -> Any:
    return rpc("fail_compute_job", {
        "p_job_id": job_id,
        "p_error": error[:2000],
        "p_result_payload": result_payload or {},
    })


def evidence_firewall(job: Dict[str, Any]) -> List[str]:
    return [
        "VERIFIED: Job was claimed from Supabase compute_jobs queue by HF Queue Worker.",
        "VERIFIED: Artifact was generated by deterministic v0.1 worker logic.",
        "INFERRED: Cost/margin comes from queued quote/route metadata, not live cloud billing telemetry.",
        "SPECULATIVE: Hyperfold Compute remains an OAE architecture metaphor, not verified new physics.",
        "LIMITATION: Output is a managed compute artifact, not a guarantee of revenue or correctness.",
    ]


def render_artifact(job: Dict[str, Any]) -> str:
    job_payload = job.get("job_payload") or {}
    task = job.get("task") or job_payload.get("task") or "No task provided."
    task_type = job.get("task_type") or job_payload.get("task_type") or "text"
    quote = job.get("quote") or {}

    if task_type == "code":
        body = """```python
#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(description='OAE Compute Relay generated CLI skeleton')
    parser.add_argument('--input', default='hello')
    args = parser.parse_args()
    print({'status': 'ok', 'input': args.input})

if __name__ == '__main__':
    main()
```"""
    else:
        body = f"""OAE Compute Relay processed this managed compute job.

Requested task:

> {task}

Result summary:

This job was routed through the v0.1 deterministic worker path. The artifact records the task, quote metadata, Evidence Firewall labels, and a stable hash so the run can be audited later.
"""

    markdown = f"""# OAE Compute Relay Artifact

**Job ID:** `{job.get('job_id')}`  
**Generated:** {utc_now()}  
**Worker:** `{WORKER_ID}`  
**Task type:** `{task_type}`  
**Status:** completed

## Task

{task}

## Output

{body}

## Quote / Route Metadata

```json
{json.dumps(quote, indent=2, ensure_ascii=False)}
```

## Evidence Firewall

{chr(10).join('- ' + item for item in evidence_firewall(job))}
"""
    return markdown


def process_once() -> Dict[str, Any]:
    job = claim_next_job()
    if not job:
        return {"status": "idle", "message": "no queued paid jobs available", "worker": WORKER_ID, "time": utc_now()}

    job_id = job.get("job_id", "unknown")
    try:
        artifact = render_artifact(job)
        artifact_sha = sha256_text(artifact)
        result_payload = {
            "worker": WORKER_ID,
            "completed_at": utc_now(),
            "artifact_markdown": artifact,
            "artifact_sha256": artifact_sha,
            "route": (job.get("quote") or {}).get("route"),
            "estimated_margin_cad": (job.get("quote") or {}).get("estimated_margin_cad"),
        }
        updated = complete_job(job_id, artifact_sha, result_payload)
        return {"status": "done", "job_id": job_id, "artifact_sha256": artifact_sha, "updated": updated}
    except Exception as exc:
        fail_result = fail_job(job_id, str(exc), {"worker": WORKER_ID, "failed_at": utc_now()})
        return {"status": "failed", "job_id": job_id, "error": str(exc), "fail_result": fail_result}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--once", action="store_true", help="Process at most one queued job")
    parser.add_argument("--dry-run", action="store_true", help="Validate config without claiming jobs")
    args = parser.parse_args()

    if args.dry_run:
        print(json.dumps({
            "status": "ok" if bool(SUPABASE_SERVICE_ROLE_KEY) else "blocked",
            "worker": WORKER_ID,
            "supabase_url": SUPABASE_URL,
            "has_service_role_key": bool(SUPABASE_SERVICE_ROLE_KEY),
            "time": utc_now(),
        }, indent=2))
        return

    result = process_once()
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
