#!/usr/bin/env python3
"""
HF Queue Worker for OAE Compute Relay v0.2

Uses Supabase anon/publishable key + OAE_RELAY_SHARED_SECRET to call secret-gated RPCs.
This avoids putting the Supabase service-role key inside HF Jobs.

Required env for live mode:
- SUPABASE_URL=https://ubauxksvewtwwerkpbuo.supabase.co
- SUPABASE_ANON_KEY=<publishable/anon key>
- OAE_RELAY_SHARED_SECRET=<relay secret>

Modes:
- --dry-run: validate config only
- --once: claim/process at most one job
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import urllib.error
import urllib.request
from typing import Any, Dict, Optional

WORKER_ID = os.getenv("OAE_WORKER_ID", "hf-secret-rpc-worker-v02")
SUPABASE_URL = os.getenv("SUPABASE_URL", "https://ubauxksvewtwwerkpbuo.supabase.co").rstrip("/")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "") or os.getenv("SUPABASE_PUBLISHABLE_KEY", "")
OAE_RELAY_SHARED_SECRET = os.getenv("OAE_RELAY_SHARED_SECRET", "")


def utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def request_json(method: str, path: str, payload: Optional[Any] = None) -> Any:
    if not SUPABASE_ANON_KEY:
        raise RuntimeError("SUPABASE_ANON_KEY is not set")
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(f"{SUPABASE_URL}{path}", data=data, method=method)
    req.add_header("content-type", "application/json")
    req.add_header("apikey", SUPABASE_ANON_KEY)
    req.add_header("authorization", f"Bearer {SUPABASE_ANON_KEY}")
    try:
        with urllib.request.urlopen(req, timeout=45) as resp:
            raw = resp.read().decode("utf-8")
            return None if not raw else json.loads(raw)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8")
        raise RuntimeError(f"HTTP {exc.code} from {path}: {body}") from exc


def rpc(name: str, payload: Dict[str, Any]) -> Any:
    return request_json("POST", f"/rest/v1/rpc/{name}", payload)


def claim_next_job() -> Optional[Dict[str, Any]]:
    result = rpc("claim_next_compute_job_with_secret", {
        "p_secret": OAE_RELAY_SHARED_SECRET,
        "p_worker_id": WORKER_ID,
    })
    if isinstance(result, list):
        return result[0] if result else None
    if isinstance(result, dict):
        return result
    return None


def complete_job(job_id: str, artifact_sha: str, result_payload: Dict[str, Any], artifact_url: Optional[str] = None) -> Any:
    return rpc("complete_compute_job_with_secret", {
        "p_secret": OAE_RELAY_SHARED_SECRET,
        "p_job_id": job_id,
        "p_artifact_sha256": artifact_sha,
        "p_result_payload": result_payload,
        "p_artifact_url": artifact_url,
    })


def fail_job(job_id: str, error: str, result_payload: Optional[Dict[str, Any]] = None) -> Any:
    return rpc("fail_compute_job_with_secret", {
        "p_secret": OAE_RELAY_SHARED_SECRET,
        "p_job_id": job_id,
        "p_error": error[:2000],
        "p_result_payload": result_payload or {},
    })


def render_artifact(job: Dict[str, Any]) -> str:
    quote = job.get("quote") or {}
    task = job.get("task") or (job.get("job_payload") or {}).get("task") or "No task provided."
    task_type = job.get("task_type") or "text"
    return f"""# OAE Compute Relay Artifact

**Job ID:** `{job.get('job_id')}`  
**Generated:** {utc_now()}  
**Worker:** `{WORKER_ID}`  
**Task type:** `{task_type}`  

## Task

{task}

## Output

The OAE Compute Relay secret-gated worker claimed this paid queued job, generated a deterministic v0.2 artifact, and returned the result through Supabase RPC.

## Route / Quote

```json
{json.dumps(quote, indent=2, ensure_ascii=False)}
```

## Evidence Firewall

- VERIFIED: Job was claimed from `compute_jobs` using secret-gated RPC.
- VERIFIED: Artifact was generated by HF Queue Worker v0.2.
- INFERRED: Cost/margin uses queue quote metadata, not live cloud billing telemetry.
- SPECULATIVE: Hyperfold Compute is an OAE architecture metaphor, not verified new physics.
- LIMITATION: This output is not a guarantee of revenue or correctness.
"""


def process_once() -> Dict[str, Any]:
    if not OAE_RELAY_SHARED_SECRET:
        return {"status": "blocked", "reason": "OAE_RELAY_SHARED_SECRET not set", "worker": WORKER_ID}
    job = claim_next_job()
    if not job:
        return {"status": "idle", "message": "no queued paid jobs available", "worker": WORKER_ID, "time": utc_now()}
    job_id = job.get("job_id", "unknown")
    try:
        artifact = render_artifact(job)
        artifact_sha = sha256_text(artifact)
        payload = {
            "worker": WORKER_ID,
            "completed_at": utc_now(),
            "artifact_markdown": artifact,
            "artifact_sha256": artifact_sha,
            "route": (job.get("quote") or {}).get("route"),
            "estimated_margin_cad": (job.get("quote") or {}).get("estimated_margin_cad"),
        }
        updated = complete_job(job_id, artifact_sha, payload)
        return {"status": "done", "job_id": job_id, "artifact_sha256": artifact_sha, "updated": updated}
    except Exception as exc:
        fail_result = fail_job(job_id, str(exc), {"worker": WORKER_ID, "failed_at": utc_now()})
        return {"status": "failed", "job_id": job_id, "error": str(exc), "fail_result": fail_result}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--once", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.dry_run:
        print(json.dumps({
            "status": "ok" if (SUPABASE_ANON_KEY and OAE_RELAY_SHARED_SECRET) else "blocked",
            "worker": WORKER_ID,
            "supabase_url": SUPABASE_URL,
            "has_anon_key": bool(SUPABASE_ANON_KEY),
            "has_relay_secret": bool(OAE_RELAY_SHARED_SECRET),
            "time": utc_now(),
        }, indent=2))
        return
    print(json.dumps(process_once(), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
