#!/usr/bin/env python3
"""
OAE Hyperfold Money Worker v0.1

Separate from LINGO.

Purpose:
- Route paid artifact jobs into cheap compute.
- Generate first artifact type: HF Opportunity Report.
- Support safe probe mode, queue mode, and future Stripe polling mode.

Evidence Firewall:
- This script does not guarantee revenue.
- This script does not send outreach.
- This script does not run paid compute unless `paid: true` or Stripe confirms payment.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List

ARTIFACT_DIR = Path(os.getenv("OAE_ARTIFACT_DIR", "artifacts"))
LEDGER_PATH = Path(os.getenv("OAE_LEDGER_PATH", "ledger.jsonl"))
STRIPE_PAYMENT_LINK = os.getenv("STRIPE_PAYMENT_LINK", "https://buy.stripe.com/00wfZh3K1gWpgkVgzs8k80e")
STRIPE_PAYMENT_LINK_ID = os.getenv("STRIPE_PAYMENT_LINK_ID", "plink_1Tbq2nFRuWOMBXuRWGwCmhIg")
PRODUCT_NAME = os.getenv("OAE_PRODUCT_NAME", "ARCH Money Agent Starter Report")
PRICE_CAD = int(os.getenv("OAE_PRICE_CAD", "19"))


def utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat()


def stable_hash(obj: Any) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest()


def ensure_dirs() -> None:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)


def evidence_block(extra: List[str] | None = None) -> str:
    labels = [
        "VERIFIED: Artifact generated by OAE Hyperfold Money Worker v0.1.",
        "VERIFIED: Product route points to a Stripe payment link.",
        "INFERRED: Recommendations are generated from supplied input and reusable business logic.",
        "SPECULATIVE: Hyperfold Compute is an architecture metaphor for routing, memory, and cost compression; not verified new physics.",
        "LIMITATION: This report is informational and does not guarantee revenue.",
    ]
    if extra:
        labels.extend(extra)
    return "\n".join(f"- {x}" for x in labels)


def generate_hf_opportunity_report(job: Dict[str, Any]) -> str:
    inp = job.get("input", {})
    idea = inp.get("idea", "AI artifact vending system")
    target_customer = inp.get("target_customer", "small businesses and solo founders")
    budget = inp.get("budget", "free/cheap compute")
    tone = inp.get("tone", "clear, practical, upbeat")
    job_id = job.get("job_id", "unknown")

    # v0.1 intentionally uses deterministic template logic so it can run cheaply and safely.
    # Later versions can call HF model_search / InferenceClient when secrets and cost caps are configured.
    return f"""# HF Opportunity Report

**Job ID:** `{job_id}`  
**Generated:** {utc_now()}  
**Product:** {job.get('product', 'HF Opportunity Report')}  
**Paid:** {bool(job.get('paid'))}  

## Input Summary

- **Idea:** {idea}
- **Target customer:** {target_customer}
- **Compute budget:** {budget}
- **Tone:** {tone}

## Best Immediate Offer

Sell a small, fixed-scope report rather than a vague AI service:

**Offer:** AI Opportunity / Build Path Report  
**Starting price:** ${PRICE_CAD} CAD  
**Checkout:** {STRIPE_PAYMENT_LINK}

The buyer pays for a finished artifact, not raw compute. This keeps the product simple, low-risk, and cheap to fulfill.

## Artifact Deliverable

The report should include:

1. Problem / market summary
2. Recommended AI artifact or automation
3. Hugging Face model categories to inspect
4. Dataset / Space inspiration paths
5. Build path: no-code, low-code, or code
6. Monetization plan
7. Compute route
8. Risk notes
9. Next-step upsell

## Compute Route

For this job type, the cheapest viable route is:

```txt
payment confirmation
→ queue job
→ template + cached OAE memory
→ optional HF model/dataset/Space search
→ small LLM polish only when needed
→ artifact markdown
→ ledger entry
→ delivery link/email
```

## Hyperfold Compute Translation

The impossible-physics/OAE framing becomes a practical compute advantage:

| OAE motif | Practical compute behavior |
|---|---|
| Temporal-Memory Spine | Reuse templates, prior reports, prompt fragments, and known patterns. |
| Non-Euclidean Folding | Group similar requests so one reusable solution serves many jobs. |
| Branch Collapse | Generate a few cheap candidate plans, then keep the most profitable/useful one. |
| Evidence Firewall | Separate verified facts, inference, and speculation in every output. |
| Stripe Spine | Do not spend meaningful compute until payment is confirmed. |

## Monetization Path

Start with one low-touch product:

```txt
$19 HF Opportunity Report
→ $49 build-path expansion
→ $149 artifact implementation plan
→ $299+ done-for-you recovery/build package
```

## Risk Notes

- Do not claim guaranteed income.
- Do not resell raw free compute.
- Do not send unsolicited spam.
- Do not run GPU jobs until payment and margin justify it.
- Do not process sensitive private client data on free-tier APIs unless terms/privacy are acceptable.

## Next Upsell

**Recommended upsell:** “I can turn this report into a launchable Hugging Face Space / GitHub repo / Stripe-backed artifact vending workflow.”

## Evidence Firewall

{evidence_block()}
"""


def write_artifact(job: Dict[str, Any], markdown: str) -> Dict[str, str]:
    ensure_dirs()
    job_id = str(job.get("job_id", "job"))
    safe_id = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in job_id)[:80]
    digest = stable_hash({"job": job, "markdown": markdown})[:12]
    md_path = ARTIFACT_DIR / f"{safe_id}-{digest}.md"
    json_path = ARTIFACT_DIR / f"{safe_id}-{digest}.json"

    artifact_record = {
        "job": job,
        "artifact_path": str(md_path),
        "artifact_sha256": stable_hash(markdown),
        "generated_at": utc_now(),
        "worker": "oae-hyperfold-money-worker-v0.1",
    }

    md_path.write_text(markdown, encoding="utf-8")
    json_path.write_text(json.dumps(artifact_record, indent=2, ensure_ascii=False), encoding="utf-8")
    append_ledger(artifact_record)
    return {"markdown": str(md_path), "json": str(json_path)}


def append_ledger(record: Dict[str, Any]) -> None:
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True) if LEDGER_PATH.parent != Path('.') else None
    with LEDGER_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_queue(path: str) -> List[Dict[str, Any]]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Queue must be a JSON list of jobs")
    return data


def process_job(job: Dict[str, Any]) -> Dict[str, Any]:
    if not job.get("paid"):
        return {"job_id": job.get("job_id"), "status": "skipped", "reason": "job is not marked paid"}
    artifact_type = job.get("product", "HF Opportunity Report").lower()
    if "opportunity" in artifact_type or "report" in artifact_type:
        markdown = generate_hf_opportunity_report(job)
    else:
        markdown = generate_hf_opportunity_report(job)
    paths = write_artifact(job, markdown)
    return {"job_id": job.get("job_id"), "status": "done", "paths": paths}


def run_probe() -> None:
    demo_job = {
        "job_id": "probe-001",
        "paid": True,
        "product": "HF Opportunity Report",
        "price_cad": PRICE_CAD,
        "customer_email": "probe@example.com",
        "input": {
            "idea": "Use OAE Hyperfold Compute to sell finished AI artifacts with cheap authorized compute.",
            "target_customer": "agents, builders, small businesses, and solo founders",
            "budget": "free/cheap authorized compute only",
            "tone": "clear, practical, energetic",
        },
    }
    result = process_job(demo_job)
    print(json.dumps({"mode": "probe", "result": result}, indent=2))


def run_queue(queue_path: str) -> None:
    jobs = load_queue(queue_path)
    results = [process_job(job) for job in jobs]
    print(json.dumps({"mode": "queue", "results": results}, indent=2))


def run_stripe_placeholder() -> None:
    # This is intentionally a placeholder until STRIPE_SECRET_KEY is available to the HF job.
    # When enabled, this should poll completed Checkout Sessions or receive webhook-created queue jobs.
    if not os.getenv("STRIPE_SECRET_KEY"):
        print(json.dumps({
            "mode": "stripe",
            "status": "blocked",
            "reason": "STRIPE_SECRET_KEY is not available inside this worker environment",
            "payment_link_id": STRIPE_PAYMENT_LINK_ID,
            "next_step": "Add a Stripe API key/webhook bridge or use ChatGPT connector as control-plane until then."
        }, indent=2))
        return
    print(json.dumps({
        "mode": "stripe",
        "status": "not_implemented_yet",
        "reason": "Stripe secret detected, but polling/webhook queue implementation is next module."
    }, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["probe", "queue", "stripe"], default="probe")
    parser.add_argument("--queue", default="queue.example.json")
    args = parser.parse_args()

    if args.mode == "probe":
        run_probe()
    elif args.mode == "queue":
        run_queue(args.queue)
    elif args.mode == "stripe":
        run_stripe_placeholder()


if __name__ == "__main__":
    main()
